# Generated by Django 5.1.1 on 2025-02-19 17:53

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_customuser_is_email_verified_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile_pics/'),
        ),
    ]
